=== zj-github/ws01/codelib/p02/src/main/resources/crawlinfo.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"
	targetNamespace="http://www.innohub.cn" elementFormDefault="qualified">
	<xs:element name='crawlinfo'>
		<xs:complexType>
			<xs:sequence maxOccurs='unbounded'>
				<xs:element name='host'>
					<xs:simpleContent>
						<xs:simpleType>
							<xs:restriction base="basetype">
								<xs:attribute name="name" type="xs:string" />
							</xs:restriction>
						</xs:simpleType>
					</xs:simpleContent>
					<xs:complexType>
						<xs:sequence>

							<xs:element name='updatefrequency' type='xs:string' />
							<xs:element name='detailpage'>
								<xs:complexType>
									<xs:sequence maxOccurs='1'>
										<xs:element name='tablename' type='xs:string' />
										<xs:element name="fields">
											<xs:complexType>
												<xs:all>
													<xs:simpleContent>
														<xs:simpleType>
															<xs:restriction base="basetype">
																<xs:attribute name="description" type="xs:string" />
															</xs:restriction>
														</xs:simpleType>
													</xs:simpleContent>
												</xs:all>
												<xs:sequence maxOccurs='unbounded'>
													<xs:element name="field">
														<xs:complexType>
															<xs:sequence>
																<xs:element name='columnname' type='xs:string' />
																<xs:element name='element' type='xs:string' />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>
</xs:schema>

=== zj-github/ws01/codelib/p02/src/main/resources/crawlinfo.xml
<?xml version="1.0" encoding="UTF-8"?>
<!-- <crawlinfo xmlns="http://www.innohub.cn" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://www.innohub.cn crawlinfo.xsd">
 -->
 <crawlinfo>
	<host name="www.renrentou.com"  url="http://www.renrentou.com/"  >
		<updatefrequency>60000</updatefrequency><!-- 更新频率 单位分钟 2 * 60 * 60 * 1000 -->
		<detailpage id="rrtpro" reg=".+www.renrentou.com/project/detail/project_id.*">
			<tablename>ccfa_common</tablename>
			<fields>
				<field description="发起人">
					<columnname>pro_name</columnname>
					<element>dl.attention-dl>dd>b'发起人：</element><!-- 发起人：陈晨, 项目地点：  -->
				</field>
				<field description="项目地点">
					<columnname>address</columnname>
					<element>p.attention-p$1</element>
				</field>
			</fields>
		</detailpage>
	</host>
	<host name="news.163.com"  url="http://news.163.com/"  >
		<updatefrequency>60000</updatefrequency><!-- 更新频率 单位分钟 2 * 60 * 60 * 1000 -->
		<detailpage id="new163" reg="http://news.163.com/\d{2}/\d{4}/\d{2}/.+.html">
			<tablename>ccfa_common2</tablename>
			<fields>
				<field description="发起人">
					<columnname>title</columnname>
					<element>h1.ep-h1</element><!-- 发起人：陈晨, 项目地点：  -->
				</field>
				<field description="项目地点">
					<columnname>comment_num</columnname>
					<element>a.ep-cnum-tie js-tielink js-tiecount JS_NTES_LOG_FE</element>
				</field>
			</fields>
		</detailpage>
	</host>
</crawlinfo>
